[build]
builder = "nixpacks"
buildCommand = """
composer install --no-dev --optimize-autoloader
php artisan config:cache
php artisan route:cache
php artisan migrate --force
"""

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[[services]]
name = "websocket"
startCommand = "php artisan reverb:start --host=0.0.0.0 --port=6001"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[[services]]
name = "queue"
startCommand = "php artisan queue:work --tries=3 --backoff=3"
